# Generated by Django 4.2.3 on 2023-07-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_countrymodel_d_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='d_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='president',
            field=models.CharField(max_length=30),
        ),
    ]
